# Generated by Django 6.0.5 on 2026-05-21 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('strength', 'Strength Training'), ('yoga', 'Yoga & Flexibility'), ('cardio', 'Cardio & HIIT'), ('crossfit', 'CrossFit'), ('swimming', 'Swimming'), ('pilates', 'Pilates'), ('general', 'General Fitness')], default='general', max_length=20)),
                ('schedule', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
