# Generated by Django 6.0.5 on 2026-05-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_received', to='members.memberprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_sent', to='trainers.trainerprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Weight Training'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('pilates', 'Pilates'), ('swimming', 'Swimming'), ('crossfit', 'CrossFit'), ('other', 'Other')], max_length=20)),
                ('duration_min', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
