# Generated by Django 6.0.5 on 2026-05-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('duration', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('predicted_calories', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
